
- include: account.yml

- name: download {{ nexus3_release }} tarball
  become_user: "{{ nexus3_user }}"
  get_url:
    url: "{{ nexus3_tar_url }}"
    dest: "{{ nexus3_tar_cache }}"

- name: extract nexus3 tar
  become_user: "{{ nexus3_user }}"
  unarchive:
    src: "{{ nexus3_tar_cache }}"
    dest: "{{ nexus3_home }}"
    creates: "{{ nexus3_dist_dir }}/NOTICE.txt"
    remote_src: yes

- name: upstart script
  template:
    src: etc/init/nexus3.conf.j2
    dest: /etc/init/nexus3.conf
    mode: 0555
    owner: root
    group: root
  notify: bounce nexus3

- name: nexus3 service
  service:
    name: nexus3
    state: started
    enabled: yes
