
- name: create {{ nexus3_group }}
  group:
    name: "{{ nexus3_group }}"

- name: create {{ nexus3_user }} account
  user:
    name: "{{ nexus3_user }}"
    group: "{{ nexus3_group }}"
    comment: Sonatype Nexus
    createhome: yes

- name: download {{ nexus3_release }} tarball
  get_url:
    url: "{{ nexus3_tar_url }}"
    dest: "{{ nexus3_tar_cache }}"

- name: extract nexus3 tar
  unarchive:
    src: "{{ nexus3_tar_cache }}"
    dest: "{{ nexus3_home_parent }}"
    creates: "{{ nexus3_home }}/NOTICE.txt"
    remote_src: yes

- name: use upstart script
  template:
    src: etc/init/nexus3.conf.j2
    dest: /etc/init/nexus3.conf
    mode: 0555
    owner: root
    group: root
  notify: bounce nexus3

- name: run as {{ nexus3_user }} from {{ nexus3_home }}
  template:
    src: ".{{ item }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - "{{ nexus3_home }}/bin/nexus.rc"
    - /etc/profile.d/nexus3.sh

- name: writable {{ nexus3_work_dir }} directory
  file:
    path: "{{ nexus3_work_dir }}"
    state: directory
    owner: "{{ nexus3_user }}"
    group: "{{ nexus3_group }}"

- name: nexus3 service
  service:
    name: nexus3
    state: started
    enabled: yes
